apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - notification-cm.yaml
  - notification-secret.yaml

  
patchesJson6902:
  - target:
      kind: Secret
      name: argocd-notifications-secret
      version: v1
    path: notification-secret.yaml

  - target:
      kind: ConfigMap
      name: argocd-notifications-cm
      version: v1
    path: notification-cm.yaml