apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  argocd.argoproj.io/managed-by: openshift-gitops

bases:
  - ../argocd-instance/base


resources:
  - appbundle-proj.yaml
  - root-app.yaml


  
