apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle
spec:
  destination:
    namespace: root-appbundle              
    server: https://kubernetes.default.svc
  project: appbundle-parent
  source:
    path: argocd/apps/keycloak/base
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master

syncPolicy:
  automated:
    prune: false
    selfHeal: 
  syncOptions:
  - CreateNamespace: true