apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-instances
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops           
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: argocd/argocd-instance/base
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master

  
  