apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: appbundle-parent
  source:
    repoURL: https://github.com/codecentric/helm-charts/
    charts: keycloak
   
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  
  
  
