apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: root-app
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloak
    targetRevision: 16.0.5

  
    
    
  
  
  
