apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd-01  
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  dex:
    openShiftOAuth: true
  rbac:    
    policy: g, argocdadmins, role:admin
    scopes: '[groups]'      
  server:
    route:
      enabled: true
