apiVersion: v1
kind: Pod
metadata:
  name: openshift-tools
spec:
  containers:
  - name: openshift-tools
    image: registry.redhat.io/openshift4/ose-tools-rhel8
    env: 
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: openshift
    # volumeMounts:
    # - name: secretpath
    #   mountPath: "/etc/secretpath"
    #   readOnly: true
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $SECRET_KEY; done"]
    
  restartPolicy: OnFailure
  # volumes:
  # - name: secretpath
  #   secret:
  #     secretName: mysecret
      # items:
      # - key: openshift
      #   path: openshift

  