apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: default 
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: cluster
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
