apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-01
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: []
  server:
    route:
      enabled: true