apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oc-practice
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "jarvis-test"
spec:
  destination:
    namespace: oc-practice            
    server: https://kubernetes.default.svc
  project: root-app
  source:
    path: argocd/apps/notification-controller
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master  
  plugin:
  name: argocd-vault-plugin
  env:
    - name: AVP_K8S_ROLE
      value: vplugin
    - name: AVP_TYPE
      value: vault
    - name: AVP_AUTH_TYPE
      value: k8s
    
    
    
    
    