apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oc-practice
spec:
  destination:
    namespace: oc-practice            
    server: https://kubernetes.default.svc
  project: root-app
  source:
    path: argocd/apps/openshift-tools
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master

  
  