apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    directory:
      recurse: true
    path: cluster-config/base
    repoURL: https://github.com/StinkyBenji/openshift-gitops-practice
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
