apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vplugin-secret
  namespace: argocd-01
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "jarvis-test"
spec:
  destination:
    namespace: argocd-01   
    server: 'https://kubernetes.default.svc'         
  project: root-app
  source:
    repoURL: 'https://github.com/StinkyBenji/openshift-gitops-practice'
    path: argocd/apps/argocd-vault-plugin
    targetRevision: master
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_K8S_ROLE
          value: vplugin
        - name: AVP_TYPE
          value: vault
        - name: AVP_VAULT_ADDR
          value: 'http://172.30.189.194:8200'
        - name: AVP_AUTH_TYPE
          value: k8s
