apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - notification-cm.yaml
  - notification-secret.yaml
  - notification-service.yaml
  - notification-sa.yaml
  - role-rbac.yaml
  - notification-deployment.yaml

configMapGenerator:
  - name: argocd-notifications-cm
    behavior: create
    files:
     - notification-cm.yaml